services:
  - type: web
    name: voig-bot
    env: node
    nodeVersion: 20
    plan: free
    buildCommand: npm install && node script/build.mjs
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
